#https://medium.com/swlh/wordpress-deployment-with-nginx-php-fpm-and-mariadb-using-docker-compose-55f59e5c1a

version: '3'

services:

  wordpress:
    image: wordpress:php7.3-fpm-alpine

    volumes:
      - data/html://var/www/html

    environment:
      WORDPRESS_DB_HOST: 
      MYSQL_ROOT_PASSWORD:
      WORDPRESS_DB_NAME: $DB_NAME
      WORDPRESS_DB_USER: $DB_USER
      WORDPRESS_DB_PASSWORD: $DB_PASSWORD
      WORDPRESS_TABLE_PREFIX: wp_
    
    restart: always

  nginx:
    image: nginx:alpine

    volumes:
      - nginx:/etc/nginx/conf.d
      - /data/html:/var/www/html/

    ports:
      - 443:443

    links:
      - wordpress
